# ==========================================================
# 📦 Render 自動デプロイ設定ファイル（無料プラン安定版）
# ==========================================================
# ※ファイル名は「render.yaml」でもOK（スマホでドット付き不可のため）
# ==========================================================

services:
  # -----------------------------
  # 🚀 メインアプリ（FastAPIサーバー）
  # -----------------------------
  - type: web
    name: boat-ai-fastapi        # ← サービス名（自由に変更OK）
    env: python
    plan: free                   # ← 無料プラン
    region: singapore            # ← 日本に最も近い無料リージョン
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000

    # ⏱️ タイムアウト対策（デフォルトより少し長め）
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: Asia/Tokyo

    # 🔁 デプロイ条件
    autoDeploy: true

  # -----------------------------
  # 🌐 静的サイト（HTML / JS / CSS 表示用）
  # -----------------------------
  - type: static
    name: boat-ai-frontend        # ← 表示名（自由に変更OK）
    env: static
    plan: free
    buildCommand: ""
    publishPath: static           # ← フロントのファイル置き場
    autoDeploy: true

    # 🔗 FastAPIと連携
    envVars:
      - key: API_URL
        value: https://boat-ai-fastapi.onrender.com

# ==========================================================
# 💡補足：
# - 1つ目：FastAPI（Pythonサーバー / API提供）
# - 2つ目：静的サイト（index.html など表示）
# - requirements.txt, app.py, static/ が存在すること
# ==========================================================
