name: Fetch Today Boat Race Data (JST対応版)

on:
  schedule:
    - cron: "0 23 * * *"   # JST 08:00 実行 (UTC 23:00)
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml pytz

      - name: Run fetch_data.py (強制出走表更新)
        run: python fetch_data.py --force-program

      - name: Run fetch_data.py (結果も更新)
        run: python fetch_data.py --force-result

      - name: Show result preview
        run: |
          echo "=== data.json preview ==="
          head -n 50 data.json || echo "data.json not found"

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes detected — skipping commit."
          else
            git commit -m "Update today's data.json (JST fetch)"
            git push
          fi