# .github/workflows/fetch-history.yml
name: Fetch Boat Race History

on:
  schedule:
    - cron: "0 0 * * 1"   # 毎週月曜 00:00 (UTC)
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run fetch_history.py
        run: python fetch_history.py

      - name: Commit and push if changed
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add history.json
          git commit -m "Update history.json (weekly auto-update)" || echo "No changes to commit"
          git push
